targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql_flutter
          addTypenameExcludedPaths:
            - subscription.*
            - subscription
